### ISSUE TITLE
Hanging at 'info: Fixing Bleno handles ...'

### ISSUE THREAD

**Issue by T08YR4D** [DigitalSecurity/btlejuice#27]
Hi, I'm very new to this but I have two VMs set up (Both Ubuntu 16.04) One is using my Mac bluetooth adapter (Proxy) and the other is using an ASUS BT dongle 4.0 (Host) When I run the proxy and the web interface they connect find and I press the shackle on a BT padlock I'm testing and it appears on the list of devices. When I double click on the device, the host hangs on 'info: Fixing Bleno handles ...' an then the device will eventually disconnect. Why is this happening?

**Comment by adrain1** [comment]
Have you solved it?

**Comment by T08YR4D** [comment]
I think the BLE device I was testing at the time was very secure and it wan't using 'JustWorks'
I don't believe it was an issue with the software.
