### ISSUE TITLE
Error to download during install

### ISSUE THREAD

**Issue by cloatre** [DigitalSecurity/btlejuice#3]
root@kali:~/BLE# npm install -g btlejuice
...
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v11-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@0.10.29 (node-v11 ABI) (falling back to source compile with node-gyp) 

-->the url does no longer exists

[Edit]
below more logs
![Uploading Screenshot from 2016-09-08 13:25:41.png…]()

**Comment by virtualabs** [comment]
> below more logs

I don't see any screenshot or further information about this issue. 

Anyway, you must install *BtleJuice* as a normal user and use *sudo* as stated in the documentation:

```
$ sudo npm install -g btlejuice
```

Trying to install as *root* will fail because of some permissions probles while installing some of the dependencies.

**Comment by cloatre** [comment]
OK I have my kali with only the user Root, I will add another user and try again.

Below the screenshot that does not work in previous post:
![screenshot from 2016-09-08 13 25 41](https://cloud.githubusercontent.com/assets/20278605/18379605/542ef54a-766b-11e6-80bd-31cebee3b410.png)

**Comment by virtualabs** [comment]
Seems your v8 version (Node.js) is too old to install the latest versions of Noble and Bleno. Upgrade Node.js (download and install the latest version) and it should be ok :)

**Comment by cloatre** [comment]
Ok thanks, I have reinstalled noble and bleno, and update nodejs to 4.x and I still look to resolve some other errors:

![capture d ecran de 2016-09-09 15 12 21](https://cloud.githubusercontent.com/assets/20278605/18387973/e8441b6e-769f-11e6-831e-b600fad32df6.png)

![capture d ecran de 2016-09-09 15 13 18](https://cloud.githubusercontent.com/assets/20278605/18387979/eed3803c-769f-11e6-9116-e83aec15b8df.png)

**Comment by virtualabs** [comment]
Check if the *nodejs* executable is installed on your system. If not, create a symlink from the *node* executable in */usr/bin*. See http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu for more details about this issue.

**Comment by bik3te** [comment]
cloatre, it looks like a previous install issue.

1. Uninstall nodejs;
2. Remove every path including node_modules (/usr/local/lib or /usr/lib or both);
3. Reinstall the last verision of nodejs;
4. Update npm (sudo npm install npm -g);
5. Reinstall btlejuice.

This should be ok then..

**Comment by cloatre** [comment]
Hello,

Ok thanks, I still have errors during installation but the proxy seems to work without errors.

I try to detect my bluetooth devices but I don't see anything an my client is disconnected when I clic on the web interface, see below:

![capture d ecran de 2016-09-20 14 58 04](https://cloud.githubusercontent.com/assets/20278605/18671035/c84f51f6-7f42-11e6-984b-ad883a0cab8e.png)

**Comment by bik3te** [comment]
Okay, I already had this issue on Ubuntu 16.04, use sudo in order to launch the proxy:
$ sudo btlejuice-proxy

If it can help, on my VM, service bluetooth is started and hciconfig hci0 is up.
On my host, service bluetooth is stopped and hciconfig hci0 is up.

**Comment by cloatre** [comment]
Ok it seems that my version of bluetooth adapter is not good:

![capture d ecran de 2016-09-20 17 05 24](https://cloud.githubusercontent.com/assets/20278605/18675980/6ac66b5c-7f54-11e6-9a76-8f2ed32a5cc7.png)

**Comment by virtualabs** [comment]
Ok, issue closed.
