### ISSUE TITLE
Could not connect the Proxy because state is unauthorized

### ISSUE THREAD

**Issue by iqtidar27** [DigitalSecurity/btlejuice#56]
Hello,
I have installed recent version of node and npm:
![Screenshot from 2019-12-29 17-09-23](https://user-images.githubusercontent.com/59121751/71563496-4ae47500-2a5e-11ea-977e-72f038bdf231.png)

After that trying to install btlejack and got this error:

![image](https://user-images.githubusercontent.com/59121751/71563507-8ed77a00-2a5e-11ea-9361-d03bf8cefcff.png)

![image](https://user-images.githubusercontent.com/59121751/71563513-a878c180-2a5e-11ea-8168-468c121e4676.png)

![image](https://user-images.githubusercontent.com/59121751/71563519-ccd49e00-2a5e-11ea-9413-5c5a625f8ab2.png)

I am using csr4.0 usb for bluetooth.
Would really appreciate any help. Thanks

**Comment by V33RU** [comment]
actually issue was nodejs - 8.10.0 
                             npm - 3.5.x
 so it will help you install properly download the 8.10.0 dpkg package and install manually

**Comment by iqtidar27** [comment]
Hi @V33RU thanks for your suggestion. Later, i have installed node v8.9.4 and npm 5.6.0. I was able to install btlejuice. But, when i am trying to connect to the proxy  it gives me below error:

![image](https://user-images.githubusercontent.com/59121751/71605750-61abca00-2b39-11ea-9c4c-57f8e1815411.png)

I am using two ubuntu 16 machine and csr4 dongle on both machines. Any suggestion is highly appreciated. 
Note: I am getting similar error for gattacker too.
