### ISSUE TITLE
Spoofing BT address

### ISSUE THREAD

**Issue by ColdHeat** [DigitalSecurity/btlejuice#7]
So I'm trying to pair my phone with a device through btlejuice and the phone does not pick up the device. 

I suspect this is due to the adapter having a different address. 

Apologies for making another ticket but is there a way to have btlejuice spoof the address of the victim device?

**Comment by ColdHeat** [comment]
I did not realize spooftooph existed so not sure if this is worth including in btlejuice but will leave it up to you whether you want to close this or not.

**Comment by virtualabs** [comment]
I usually use [bdaddr](https://ubuntuforums.org/archive/index.php/t-925611.html) combined with a CSR 4.0 BT USB dongle to spoof a bluetooth (MAC) address. 

Have you already paired your device with your phone ? Does it rely on BT bonding or just some kind of application-level pairing ?

**Comment by virtualabs** [comment]
Considering it solved, issue closed.
